packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

linkWorkspacePackages: true

allowBuilds:
  sharp: true
  unrs-resolver: true

peerDependencyRules:
  allowedVersions:
    "openapi-typescript>typescript": "6"
