#!/usr/bin/env bash

set -euo pipefail

REPO="ktul15/multi-vendor-e-commerce-app"

ensure_label() {
  gh label create "$1" --repo "$REPO" --color "$2" --description "$3" --force >/dev/null
}

ensure_milestone() {
  local title="$1"
  local description="$2"
  if ! gh api "repos/$REPO/milestones?state=all&per_page=100" --jq ".[] | select(.title == \"$title\") | .title" | grep -Fxq "$title"; then
    gh api "repos/$REPO/milestones" -f title="$title" -f description="$description" >/dev/null
  fi
}

create_issue() {
  local title="$1"
  local labels="$2"
  local milestone="$3"
  local body="$4"
  local existing
  existing="$(gh issue list --repo "$REPO" --state all --limit 200 --search "$title in:title" --json title --jq ".[] | select(.title == \"$title\") | .title")"
  if [[ "$existing" == "$title" ]]; then
    echo "skip: $title"
    return
  fi
  gh issue create --repo "$REPO" --title "$title" --label "$labels" --milestone "$milestone" --body "$body"
}

ensure_label "web-migration" "1D76DB" "Migration of Flutter dashboards to Next.js"
ensure_label "shared-web" "5319E7" "Shared web workspace, UI, schemas, and API client"
ensure_label "security" "B60205" "Authentication, authorization, and application security"
ensure_label "accessibility" "0E8A16" "Accessibility and keyboard interaction"
ensure_label "observability" "006B75" "Logging, monitoring, analytics, and diagnostics"
ensure_label "vendor-dash" "F9D0C4" "Vendor dashboard work"
ensure_label "admin-dash" "C5DEF5" "Admin dashboard work"

ensure_milestone "M9 — Web Migration Discovery" "Inventory Flutter dashboard behavior and stabilize contracts for the Next.js migration."
ensure_milestone "M10 — Web Foundation & Auth" "Create the shared Next.js workspace, design system, API client, and browser-safe authentication."
ensure_milestone "M11 — Vendor Dashboard Web" "Reach feature parity for the vendor dashboard in Next.js."
ensure_milestone "M12 — Vendor Web Validation" "Harden and validate the vendor web dashboard before reusing the foundation for admin."
ensure_milestone "M13 — Admin Panel Web" "Reach feature parity for the admin panel in Next.js."
ensure_milestone "M14 — Web QA & Deployment" "Complete cross-dashboard testing, security, accessibility, observability, and production deployment."
ensure_milestone "M15 — Dashboard Cutover" "Roll out the Next.js dashboards and retire the legacy Flutter dashboard apps safely."

# M9 — Discovery
create_issue "Document vendor dashboard migration parity matrix" "vendor-dash,web-migration,priority:high" "M9 — Web Migration Discovery" $'Inventory every vendor Flutter route, user action, API call, state, and edge case.\n\n**Acceptance Criteria:**\n- [ ] Login, registration, approval gate, dashboard, products, orders, earnings, store, and Stripe Connect are covered\n- [ ] Each row identifies current route, endpoint, permissions, and target web route\n- [ ] Loading, empty, validation, error, and success behavior is recorded\n- [ ] Known Flutter defects are marked as fix-during-migration or preserve behavior\n- [ ] Product variant and order-status rules are explicitly documented'
create_issue "Document admin panel migration parity matrix" "admin-dash,web-migration,priority:high" "M9 — Web Migration Discovery" $'Inventory every admin Flutter route, action, API call, state, and edge case.\n\n**Acceptance Criteria:**\n- [ ] Dashboard, users, vendors, moderation, orders, finance, categories, promos, banners, and settings are covered\n- [ ] Each row identifies current route, endpoint, permissions, and target web route\n- [ ] Destructive actions and confirmations are identified\n- [ ] Loading, empty, validation, error, and success behavior is recorded\n- [ ] Placeholder functionality is clearly separated from parity requirements'
create_issue "Audit dashboard API contracts and OpenAPI coverage" "backend,shared-web,web-migration,priority:high" "M9 — Web Migration Discovery" $'Validate backend contracts used by both dashboards and make the migration gaps visible.\n\n**Acceptance Criteria:**\n- [ ] Every vendor and admin request is mapped to an endpoint\n- [ ] Request, response, pagination, filtering, and error shapes are documented\n- [ ] Missing or inaccurate OpenAPI definitions are listed\n- [ ] Upload and Stripe redirect contracts are documented\n- [ ] Contract gaps become linked follow-up issues'
create_issue "Define Next.js dashboard architecture and engineering conventions" "shared-web,web-migration,setup,priority:high" "M9 — Web Migration Discovery" $'Record the architectural decisions that both web dashboards will follow.\n\n**Acceptance Criteria:**\n- [ ] App Router, rendering, caching, and client-component boundaries are defined\n- [ ] Workspace, package ownership, imports, and naming conventions are defined\n- [ ] TanStack Query, forms, validation, tables, charts, and uploads have standard patterns\n- [ ] Authentication and authorization boundaries are documented\n- [ ] Testing and deployment conventions are included'
create_issue "Define migration rollout, rollback, and parity sign-off process" "web-migration,devops,testing,priority:high" "M9 — Web Migration Discovery" $'Define how the web dashboards will run alongside Flutter and how parity will be approved.\n\n**Acceptance Criteria:**\n- [ ] Staging, limited rollout, production cutover, and rollback stages are defined\n- [ ] Vendor and admin parity owners/checklists are defined\n- [ ] Data compatibility and backward compatibility requirements are documented\n- [ ] Legacy Flutter freeze and archive criteria are defined\n- [ ] Go/no-go checklist is agreed'

# M10 — Foundation and auth
create_issue "Initialize pnpm and Turborepo web workspace" "shared-web,web-migration,setup,priority:high" "M10 — Web Foundation & Auth" $'Create the monorepo foundation for both Next.js dashboards.\n\n**Acceptance Criteria:**\n- [ ] apps/vendor-dashboard and apps/admin-panel are scaffolded with Next.js and strict TypeScript\n- [ ] Shared packages for UI, API client, schemas, config, auth, and test utilities exist\n- [ ] Root development, build, lint, type-check, and test commands work\n- [ ] Environment examples are provided for both apps\n- [ ] Existing backend and Flutter commands remain unaffected'
create_issue "Configure shared linting formatting and CI quality gates for web apps" "shared-web,web-migration,devops,testing,priority:high" "M10 — Web Foundation & Auth" $'Add consistent automated quality checks for the web workspace.\n\n**Acceptance Criteria:**\n- [ ] Shared strict TypeScript, ESLint, and Prettier configuration is used\n- [ ] CI runs lint, type-check, unit tests, and production builds\n- [ ] Workspace caching is configured safely\n- [ ] Pull requests fail on any required web check\n- [ ] Commands are documented in the repository README'
create_issue "Build shared dashboard design tokens and component primitives" "shared-web,web-migration,ui/ux,accessibility,priority:high" "M10 — Web Foundation & Auth" $'Create the common visual and interaction foundation for admin and vendor apps.\n\n**Acceptance Criteria:**\n- [ ] Colors, typography, spacing, radii, shadows, and status colors are defined\n- [ ] Buttons, inputs, selects, dialogs, badges, cards, skeletons, empty states, and errors are available\n- [ ] Components support keyboard navigation and visible focus\n- [ ] Components work at desktop and tablet breakpoints\n- [ ] Shared components are documented with representative states'
create_issue "Build shared responsive dashboard shell and navigation" "shared-web,web-migration,ui/ux,priority:high" "M10 — Web Foundation & Auth" $'Implement the reusable dashboard layout.\n\n**Acceptance Criteria:**\n- [ ] Desktop sidebar, tablet drawer, header, breadcrumbs, and account menu are implemented\n- [ ] Active navigation and nested routes are accessible\n- [ ] Loading and route error boundaries are included\n- [ ] Vendor and admin navigation can be configured independently\n- [ ] Layout avoids overflow at supported breakpoints'
create_issue "Create generated typed API client and shared response handling" "backend,shared-web,web-migration,priority:high" "M10 — Web Foundation & Auth" $'Provide one typed client for both web dashboards.\n\n**Acceptance Criteria:**\n- [ ] Client types are generated from or checked against OpenAPI\n- [ ] API success envelopes, field errors, and general errors are normalized\n- [ ] Query parameters, multipart uploads, and cancellation are supported\n- [ ] Authentication credentials are included safely\n- [ ] Generation and drift-check commands run in CI'
create_issue "Add browser-safe cookie authentication to backend" "backend,auth,security,web-migration,priority:high" "M10 — Web Foundation & Auth" $'Support web sessions without placing refresh tokens in browser storage.\n\n**Acceptance Criteria:**\n- [ ] Login can issue HttpOnly Secure SameSite cookies for web clients\n- [ ] Refresh rotates tokens and updates cookies\n- [ ] Logout invalidates the refresh token and clears cookies\n- [ ] Existing bearer-token Flutter clients remain compatible\n- [ ] Cookie behavior has backend integration tests'
create_issue "Harden CORS CSRF and security headers for dashboard origins" "backend,security,web-migration,priority:high" "M10 — Web Foundation & Auth" $'Secure cookie-authenticated browser requests.\n\n**Acceptance Criteria:**\n- [ ] Exact storefront, vendor, and admin origins are configurable\n- [ ] Credentialed CORS is restricted correctly\n- [ ] CSRF protection is applied to cookie-authenticated mutations\n- [ ] Production security headers are verified\n- [ ] Rejected origin and CSRF scenarios have tests'
create_issue "Implement shared web session role guards and unauthorized handling" "shared-web,auth,security,web-migration,priority:high" "M10 — Web Foundation & Auth" $'Create reusable server-aware session protection for both dashboards.\n\n**Acceptance Criteria:**\n- [ ] Protected routes reject missing or expired sessions\n- [ ] Vendor and admin roles are enforced independently\n- [ ] Wrong-role users see access denied without protected data flashing\n- [ ] Refresh is single-flight and redirects to login when unrecoverable\n- [ ] Login return paths and logout redirects are tested'
create_issue "Configure TanStack Query forms validation tables and test harness" "shared-web,web-migration,setup,testing,priority:high" "M10 — Web Foundation & Auth" $'Establish reusable application patterns before feature migration.\n\n**Acceptance Criteria:**\n- [ ] Query provider and cache defaults are defined\n- [ ] React Hook Form and Zod helpers surface field-level API errors\n- [ ] TanStack Table supports URL-backed pagination sorting and filters\n- [ ] Vitest, Testing Library, MSW, and Playwright are configured\n- [ ] Example query, form, table, and test demonstrate the conventions'

# M11 — Vendor dashboard
create_issue "Build vendor web login registration and logout flows" "vendor-dash,auth,web-migration,ui/ux,priority:high" "M11 — Vendor Dashboard Web" $'Migrate vendor account entry flows to Next.js.\n\n**Acceptance Criteria:**\n- [ ] Login and registration forms match backend validation\n- [ ] Only vendor accounts can enter the dashboard\n- [ ] Session restoration, refresh, logout, and return URL behavior work\n- [ ] Loading and field-specific errors are user friendly\n- [ ] Auth flows have component and E2E coverage'
create_issue "Build vendor approval and suspension access gate" "vendor-dash,auth,web-migration,priority:high" "M11 — Vendor Dashboard Web" $'Represent vendor lifecycle restrictions consistently.\n\n**Acceptance Criteria:**\n- [ ] Pending, rejected, suspended, and approved states have distinct UI\n- [ ] Restricted vendors cannot render or call protected feature mutations\n- [ ] Store-profile access follows the backend rules\n- [ ] Status changes appear after refresh without stale access\n- [ ] All lifecycle states are tested'
create_issue "Build vendor dashboard summary and recent orders" "vendor-dash,web-migration,feature,ui/ux,priority:high" "M11 — Vendor Dashboard Web" $'Migrate the vendor overview page.\n\n**Acceptance Criteria:**\n- [ ] Summary metrics and INR formatting match backend data\n- [ ] Sales chart and recent orders are implemented\n- [ ] Date-range controls use URL state where applicable\n- [ ] Loading, empty, partial, and error states are handled\n- [ ] Layout is responsive and accessible'
create_issue "Build vendor product list filtering and actions" "vendor-dash,web-migration,feature,ui/ux,priority:high" "M11 — Vendor Dashboard Web" $'Create the vendor inventory table and actions.\n\n**Acceptance Criteria:**\n- [ ] Server-backed pagination, search, filters, and sorting are implemented\n- [ ] Price, stock, moderation, and availability states are clear\n- [ ] Edit and delete actions enforce confirmations and permissions\n- [ ] Filters survive refresh through URL parameters\n- [ ] Loading, empty, and failure states are tested'
create_issue "Build vendor product create and edit form" "vendor-dash,web-migration,feature,ui/ux,priority:high" "M11 — Vendor Dashboard Web" $'Migrate product authoring to full Next.js pages.\n\n**Acceptance Criteria:**\n- [ ] /products/new and /products/[id]/edit routes are implemented\n- [ ] Name, description, price, category, images, variants, and inventory are supported\n- [ ] Client validation mirrors backend limits and displays field errors\n- [ ] Unsaved-change protection and submission states are implemented\n- [ ] Create and edit flows have integration coverage'
create_issue "Build hierarchical category selector for vendor products" "vendor-dash,shared-web,web-migration,ui/ux,accessibility,priority:high" "M11 — Vendor Dashboard Web" $'Provide an understandable parent/child category selection experience.\n\n**Acceptance Criteria:**\n- [ ] Parent and child categories are visually differentiated\n- [ ] Search and long labels remain readable\n- [ ] Disabled or invalid selections cannot be submitted\n- [ ] Selection works by keyboard and screen reader\n- [ ] The component supports create and edit forms'
create_issue "Build vendor product variants and inventory editor" "vendor-dash,web-migration,feature,priority:high" "M11 — Vendor Dashboard Web" $'Implement safe product variant and stock authoring.\n\n**Acceptance Criteria:**\n- [ ] At least one valid variant is required when required by the product contract\n- [ ] Size color SKU price adjustment and stock can be edited\n- [ ] Duplicate or incomplete combinations are rejected\n- [ ] Total availability cannot disagree with variant stock\n- [ ] Add update and validation scenarios are tested'
create_issue "Build vendor image upload and product media management" "vendor-dash,web-migration,feature,ui/ux,priority:high" "M11 — Vendor Dashboard Web" $'Support reliable product image management.\n\n**Acceptance Criteria:**\n- [ ] File type size count and ordering rules are enforced\n- [ ] Preview progress retry remove and failure states are implemented\n- [ ] Existing media is preserved correctly during edits\n- [ ] Upload requests use the typed API client\n- [ ] Keyboard and accessible labels are supported'
create_issue "Build vendor orders list detail and status progression" "vendor-dash,web-migration,feature,ui/ux,priority:high" "M11 — Vendor Dashboard Web" $'Migrate vendor order management.\n\n**Acceptance Criteria:**\n- [ ] Orders support server-side pagination filters and search\n- [ ] Order details show items customer shipment totals and payment state\n- [ ] Only backend-allowed next statuses are offered\n- [ ] No dropdown is rendered when only one direct action is available\n- [ ] Status updates handle confirmation concurrency and errors'
create_issue "Build vendor earnings analytics and payout history" "vendor-dash,payments,web-migration,feature,ui/ux,priority:high" "M11 — Vendor Dashboard Web" $'Migrate earnings and payout reporting.\n\n**Acceptance Criteria:**\n- [ ] Revenue commission net earnings and INR formatting are correct\n- [ ] Date range chart top products and payout history are implemented\n- [ ] Empty and unavailable payout states are explained\n- [ ] Server totals are not recomputed inconsistently in the browser\n- [ ] Reporting views have representative tests'
create_issue "Build vendor store profile management" "vendor-dash,web-migration,feature,ui/ux,priority:high" "M11 — Vendor Dashboard Web" $'Migrate vendor store settings and public-profile fields.\n\n**Acceptance Criteria:**\n- [ ] Existing profile values load into an editable form\n- [ ] Text and media validation mirrors backend rules\n- [ ] Save progress success and field errors are handled\n- [ ] Pending and suspended vendors follow documented access rules\n- [ ] Refresh displays persisted values'
create_issue "Build Stripe Connect onboarding return and refresh flows for vendor web" "vendor-dash,payments,web-migration,security,priority:high" "M11 — Vendor Dashboard Web" $'Complete browser-based Stripe Connect onboarding.\n\n**Acceptance Criteria:**\n- [ ] Onboarding starts only for the authenticated vendor\n- [ ] Return and refresh routes reconcile account status with the backend\n- [ ] Incomplete restricted active and failed states are explained\n- [ ] Redirect and replay edge cases are safe\n- [ ] Test-mode end-to-end steps are documented and verified'

# M12 — Vendor validation
create_issue "Add vendor web unit and component test coverage" "vendor-dash,web-migration,testing,priority:high" "M12 — Vendor Web Validation" $'Cover vendor business rules and UI states below the E2E layer.\n\n**Acceptance Criteria:**\n- [ ] Auth approval variants inventory status and formatting utilities are covered\n- [ ] Forms tables dialogs error states and upload states have component tests\n- [ ] API behavior is isolated with MSW\n- [ ] Critical regression paths are required in CI\n- [ ] Tests are deterministic and documented'
create_issue "Add vendor web Playwright end-to-end suite" "vendor-dash,web-migration,testing,priority:high" "M12 — Vendor Web Validation" $'Automate complete vendor workflows against seeded test data.\n\n**Acceptance Criteria:**\n- [ ] Registration approval login and logout are covered\n- [ ] Product create edit variant inventory and delete are covered\n- [ ] Order progression is covered\n- [ ] Earnings store and Stripe Connect status are covered\n- [ ] Failure artifacts are uploaded by CI'
create_issue "Run vendor dashboard Flutter-to-Next parity audit" "vendor-dash,web-migration,testing,priority:high" "M12 — Vendor Web Validation" $'Perform formal parity sign-off before building admin on the shared foundation.\n\n**Acceptance Criteria:**\n- [ ] Every parity-matrix row is demonstrated or explicitly deferred\n- [ ] Backend request and response behavior matches production contracts\n- [ ] Known regressions have blocking issues\n- [ ] Desktop and tablet layouts are reviewed\n- [ ] Product order and payout owners approve the result'
create_issue "Audit vendor web accessibility and responsive behavior" "vendor-dash,web-migration,accessibility,ui/ux,priority:medium" "M12 — Vendor Web Validation" $'Validate vendor workflows beyond happy-path desktop mouse usage.\n\n**Acceptance Criteria:**\n- [ ] Automated accessibility checks pass on critical pages\n- [ ] Core workflows are keyboard operable\n- [ ] Focus order dialogs labels contrast and errors are reviewed\n- [ ] Supported tablet and desktop widths avoid overflow\n- [ ] Findings are fixed or tracked before cutover'
create_issue "Harden vendor web performance caching and concurrency" "vendor-dash,web-migration,priority:medium" "M12 — Vendor Web Validation" $'Make vendor operations reliable under realistic browser behavior.\n\n**Acceptance Criteria:**\n- [ ] Bundle and route performance baselines are recorded\n- [ ] Query invalidation avoids stale inventory orders and vendor status\n- [ ] Duplicate form submissions and status updates are prevented\n- [ ] Large tables and images remain responsive\n- [ ] Multi-tab session and update behavior is verified'

# M13 — Admin panel
create_issue "Build admin web login session and responsive shell" "admin-dash,auth,web-migration,ui/ux,priority:high" "M13 — Admin Panel Web" $'Apply the validated shared foundation to the admin application.\n\n**Acceptance Criteria:**\n- [ ] Admin login logout restoration and expiry behavior work\n- [ ] Only ADMIN accounts can access protected routes\n- [ ] Admin navigation covers every parity route\n- [ ] Responsive shell and route boundaries are implemented\n- [ ] Auth and navigation have tests'
create_issue "Build admin dashboard overview" "admin-dash,web-migration,feature,ui/ux,priority:high" "M13 — Admin Panel Web" $'Migrate the platform overview dashboard.\n\n**Acceptance Criteria:**\n- [ ] Existing summary metrics and charts are represented accurately\n- [ ] INR and date formatting use shared utilities\n- [ ] Recent or actionable platform activity is displayed\n- [ ] Loading empty partial and error states are handled\n- [ ] Responsive behavior is tested'
create_issue "Build admin user management list and detail" "admin-dash,web-migration,feature,ui/ux,priority:high" "M13 — Admin Panel Web" $'Migrate user administration workflows.\n\n**Acceptance Criteria:**\n- [ ] User list supports server pagination search filters and URL state\n- [ ] User details expose the existing administrative information\n- [ ] Role and account-state operations require confirmation\n- [ ] Unauthorized or invalid transitions are handled\n- [ ] List detail and mutation flows are tested'
create_issue "Build admin vendor review and lifecycle management" "admin-dash,web-migration,feature,ui/ux,priority:high" "M13 — Admin Panel Web" $'Migrate vendor approval and enforcement workflows.\n\n**Acceptance Criteria:**\n- [ ] Vendor list and detail show profile status and relevant account data\n- [ ] Approve reject and suspend actions are supported\n- [ ] Required reasons and confirmations are enforced\n- [ ] Lists refresh consistently after mutations\n- [ ] Pending approved rejected and suspended flows are tested'
create_issue "Build admin vendor commission management" "admin-dash,payments,web-migration,feature,priority:high" "M13 — Admin Panel Web" $'Provide safe default and per-vendor commission controls.\n\n**Acceptance Criteria:**\n- [ ] Current default and vendor overrides are clearly differentiated\n- [ ] Percentage validation matches backend rules\n- [ ] Changes require explicit confirmation\n- [ ] Updated commission values refresh dependent views\n- [ ] Invalid and failed changes are tested'
create_issue "Build admin product moderation list and detail" "admin-dash,web-migration,feature,ui/ux,priority:high" "M13 — Admin Panel Web" $'Migrate product review and enforcement workflows.\n\n**Acceptance Criteria:**\n- [ ] Moderation list supports server pagination search filters and URL state\n- [ ] Product details show vendor category media variants price and stock\n- [ ] Activate deactivate and delete actions follow backend permissions\n- [ ] Destructive actions require confirmation\n- [ ] Moderation mutations and stale-data cases are tested'
create_issue "Build admin orders list and detail" "admin-dash,web-migration,feature,ui/ux,priority:high" "M13 — Admin Panel Web" $'Migrate platform-wide order visibility.\n\n**Acceptance Criteria:**\n- [ ] Orders support server pagination search filters and URL state\n- [ ] Details show customer vendors items totals payment and fulfillment states\n- [ ] Status and payment labels are consistent with backend values\n- [ ] Loading empty and error states are implemented\n- [ ] List-to-detail navigation and refresh behavior are tested'
create_issue "Build admin category hierarchy and CRUD" "admin-dash,web-migration,feature,ui/ux,accessibility,priority:high" "M13 — Admin Panel Web" $'Migrate hierarchical category administration.\n\n**Acceptance Criteria:**\n- [ ] Parent and child categories are visually differentiated\n- [ ] Create edit image upload and delete are supported\n- [ ] Invalid parent cycles and unsafe deletes are prevented or explained\n- [ ] Long names and deep paths remain usable\n- [ ] Keyboard behavior and CRUD flows are tested'
create_issue "Build admin promo code management" "admin-dash,web-migration,feature,ui/ux,priority:medium" "M13 — Admin Panel Web" $'Migrate promo code CRUD and validation.\n\n**Acceptance Criteria:**\n- [ ] Promo list create and edit routes are implemented\n- [ ] Discount limits dates usage and activation rules mirror backend validation\n- [ ] Delete and deactivation actions require confirmation\n- [ ] Server field errors are mapped to the form\n- [ ] Active expired scheduled and invalid cases are tested'
create_issue "Build admin banner management and preview" "admin-dash,web-migration,feature,ui/ux,priority:medium" "M13 — Admin Panel Web" $'Migrate storefront banner administration.\n\n**Acceptance Criteria:**\n- [ ] Banner list create edit preview and delete are implemented\n- [ ] Media upload has preview progress and retry behavior\n- [ ] Link ordering activation and date rules mirror backend behavior\n- [ ] Destructive actions require confirmation\n- [ ] CRUD and upload failure paths are tested'
create_issue "Build admin finance revenue and payout reporting" "admin-dash,payments,web-migration,feature,ui/ux,priority:high" "M13 — Admin Panel Web" $'Migrate platform finance reporting.\n\n**Acceptance Criteria:**\n- [ ] Revenue commission vendor earnings and payout metrics are accurate\n- [ ] INR and date range formatting are consistent\n- [ ] Charts and tables use backend totals and server filtering\n- [ ] Empty delayed and failed financial data states are explained\n- [ ] Representative financial calculations and views are tested'
create_issue "Define and implement admin web settings requirements" "admin-dash,web-migration,feature,priority:low" "M13 — Admin Panel Web" $'Resolve the existing settings placeholder before claiming full parity.\n\n**Acceptance Criteria:**\n- [ ] Product owner decides which settings belong in scope\n- [ ] Unsupported settings are removed from navigation rather than left as placeholders\n- [ ] Approved settings have API contracts authorization and UI\n- [ ] Mutation and audit requirements are documented\n- [ ] Implemented settings have tests'

# M14 — QA and deployment
create_issue "Add admin web unit and component test coverage" "admin-dash,web-migration,testing,priority:high" "M14 — Web QA & Deployment" $'Cover admin business rules and UI states below the E2E layer.\n\n**Acceptance Criteria:**\n- [ ] Permissions statuses commissions moderation and hierarchy utilities are covered\n- [ ] Forms tables dialogs uploads and error states have component tests\n- [ ] API behavior is isolated with MSW\n- [ ] Critical regression paths are required in CI\n- [ ] Tests are deterministic'
create_issue "Add admin web Playwright end-to-end suite" "admin-dash,web-migration,testing,priority:high" "M14 — Web QA & Deployment" $'Automate critical administration workflows against seeded test data.\n\n**Acceptance Criteria:**\n- [ ] Admin auth and wrong-role denial are covered\n- [ ] User vendor and product moderation workflows are covered\n- [ ] Orders categories promos banners and finance are covered\n- [ ] Destructive confirmations and failure states are exercised\n- [ ] Failure artifacts are uploaded by CI'
create_issue "Create deterministic web E2E seed and cleanup workflow" "backend,database,web-migration,testing,priority:high" "M14 — Web QA & Deployment" $'Provide isolated data for dashboard end-to-end tests.\n\n**Acceptance Criteria:**\n- [ ] Admin vendors in every lifecycle state products variants orders promos and banners are seeded\n- [ ] Seed identifiers are stable enough for tests without sharing mutable production data\n- [ ] Cleanup respects foreign keys and can run repeatedly\n- [ ] Stripe-dependent states have safe test fixtures\n- [ ] Local and CI usage is documented'
create_issue "Complete cross-dashboard security review" "backend,shared-web,security,web-migration,priority:high" "M14 — Web QA & Deployment" $'Review the web attack surface before production rollout.\n\n**Acceptance Criteria:**\n- [ ] Authentication authorization CSRF CORS cookies and logout are reviewed\n- [ ] IDOR and role-boundary tests cover vendor and admin endpoints\n- [ ] Upload and redirect inputs are validated\n- [ ] Secrets and sensitive responses are not exposed to the client\n- [ ] Blocking findings are fixed and regression-tested'
create_issue "Complete cross-dashboard accessibility review" "shared-web,web-migration,accessibility,ui/ux,priority:medium" "M14 — Web QA & Deployment" $'Validate accessible operation across both dashboards.\n\n**Acceptance Criteria:**\n- [ ] Automated checks run against critical routes\n- [ ] Keyboard-only workflows cover navigation forms tables and dialogs\n- [ ] Focus labels headings contrast live errors and status announcements are reviewed\n- [ ] Charts and status colors have nonvisual alternatives\n- [ ] Blocking findings are fixed before cutover'
create_issue "Add web dashboard observability and operational diagnostics" "shared-web,web-migration,observability,devops,priority:high" "M14 — Web QA & Deployment" $'Make production failures diagnosable without leaking sensitive data.\n\n**Acceptance Criteria:**\n- [ ] Client and server errors are captured with environment release and route context\n- [ ] Sensitive tokens payment data and personal data are redacted\n- [ ] Core auth API upload and mutation failures have useful telemetry\n- [ ] Source maps are managed securely\n- [ ] Alert ownership and triage steps are documented'
create_issue "Deploy vendor and admin Next.js apps to staging and production" "vendor-dash,admin-dash,web-migration,devops,priority:high" "M14 — Web QA & Deployment" $'Create repeatable deployments for both dashboards.\n\n**Acceptance Criteria:**\n- [ ] Vendor and admin have separate staging and production origins\n- [ ] Environment variables CORS cookie domains and Stripe return URLs are configured\n- [ ] Preview and production builds run quality gates\n- [ ] Health checks monitoring and rollback procedures are available\n- [ ] Deployment and incident documentation is complete'
create_issue "Run full admin panel Flutter-to-Next parity audit" "admin-dash,web-migration,testing,priority:high" "M14 — Web QA & Deployment" $'Perform formal admin parity sign-off before production cutover.\n\n**Acceptance Criteria:**\n- [ ] Every parity-matrix row is demonstrated or explicitly deferred\n- [ ] All high-risk mutations and permission boundaries are verified\n- [ ] Desktop and tablet layouts are reviewed\n- [ ] Blocking regressions have resolved issues\n- [ ] Admin stakeholders approve the result'

# M15 — Cutover
create_issue "Run internal dashboard migration acceptance testing" "vendor-dash,admin-dash,web-migration,testing,priority:high" "M15 — Dashboard Cutover" $'Exercise the complete migration release candidate in staging.\n\n**Acceptance Criteria:**\n- [ ] Vendor and admin parity checklists are complete\n- [ ] Seeded E2E suites and manual exploratory testing pass\n- [ ] Authentication uploads Stripe redirects and critical mutations are verified\n- [ ] Performance accessibility and security blockers are closed\n- [ ] Signed release candidate is recorded'
create_issue "Run limited vendor and admin web rollout" "vendor-dash,admin-dash,web-migration,devops,priority:high" "M15 — Dashboard Cutover" $'Expose the web dashboards to a controlled user group before full cutover.\n\n**Acceptance Criteria:**\n- [ ] Cohort and feedback channel are defined\n- [ ] Flutter dashboards remain available as rollback\n- [ ] Errors latency auth failures and mutation failures are monitored\n- [ ] Feedback is classified and blocking issues are resolved\n- [ ] Full-rollout decision is documented'
create_issue "Cut over production traffic to Next.js dashboards" "vendor-dash,admin-dash,web-migration,devops,priority:high" "M15 — Dashboard Cutover" $'Make the Next.js applications the primary vendor and admin experiences.\n\n**Acceptance Criteria:**\n- [ ] Production URLs point to the correct Next.js deployments\n- [ ] Sessions CORS cookies redirects and Stripe return URLs work in production\n- [ ] Monitoring and support coverage are active\n- [ ] Rollback procedure is tested and available\n- [ ] Cutover result and outstanding non-blockers are recorded'
create_issue "Freeze and document legacy Flutter dashboards" "vendor-dash,admin-dash,web-migration,priority:medium" "M15 — Dashboard Cutover" $'Stop feature development in the old dashboard clients while preserving rollback capability.\n\n**Acceptance Criteria:**\n- [ ] Legacy READMEs identify the Next.js replacements\n- [ ] Flutter dashboards receive only cutover-blocking fixes during the rollback window\n- [ ] Last supported commits and build instructions are recorded\n- [ ] CI expectations for legacy apps are explicitly defined\n- [ ] No legacy source is deleted during the rollback window'
create_issue "Archive legacy Flutter vendor and admin applications after rollback window" "vendor-dash,admin-dash,web-migration,devops,priority:low" "M15 — Dashboard Cutover" $'Retire the Flutter dashboard applications after stable production operation.\n\n**Acceptance Criteria:**\n- [ ] Rollback window has elapsed with no unresolved blockers\n- [ ] Source history and release artifacts remain recoverable\n- [ ] Obsolete CI deployment and environment configuration is removed safely\n- [ ] Repository documentation reflects the final architecture\n- [ ] Archive decision and date are recorded'

echo "Next.js migration issue setup complete."
